function bin = segmentImage(im)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(RGB) segments image RGB using
%  auto-generated code from the imageSegmenter app. The final segmentation
%  is returned in BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 13-Jan-2021
%----------------------------------------------------


[f, c, ~] = size(im);
% Creamos una imagen de 400x400 todo a ceros (negro)
bin = zeros(f, c);

centerX = round(f/2);
centerY = round(c/2);

p = 0.8;
offsetX = (f*(p/2));
offsetY = (c*(p/2));

% Pintamos un cuadrado blanco en el centro
bin(centerX-offsetX:centerX+offsetX, centerY-offsetY:centerY+offsetY) = 1;

end

